import { ArrowDownTrayIcon, PencilSquareIcon, TrashIcon } from "@heroicons/react/24/outline";

export const CUSTOMER_CONFIG = {
  label: "Customer",
  searchPlaceholder: "Cari customer...",
  lastIdLabel: "Customer",
  seed: [
    {
      id: 195,
      name: "PT Sinar Logistik Utama",
      account: "1101 - Piutang Usaha",
      phone: "021-555-0195",
      contactName: "Rina Lestari",
      marketing: "Andi Pratama",
      branch: "Jakarta Barat",
      status: "Active",
      pricePerKoli: "12500",
      trucking: "Truck Fuso / Reguler",
    },
    {
      id: 194,
      name: "CV Maju Bersama",
      account: "1102 - Piutang Customer",
      phone: "031-777-0194",
      contactName: "Budi Hartono",
      marketing: "Sinta Wulandari",
      branch: "Surabaya",
      status: "Active",
      pricePerKoli: "11800",
      trucking: "Wing Box / Express",
    },
    {
      id: 193,
      name: "UD Nusantara Sejahtera",
      account: "1103 - Piutang Dagang",
      phone: "022-888-0193",
      contactName: "Dewi Amalia",
      marketing: "Fajar Nugroho",
      branch: "Bandung",
      status: "Inactive",
      pricePerKoli: "13250",
      trucking: "CDE / Regular",
    },
  ],
  fields: [
    { key: "name", label: "Nama", required: true },
    { key: "account", label: "Akun", required: true },
    { key: "phone", label: "No. Telp", required: true },
    { key: "contactName", label: "Nama Kontak", required: true },
    { key: "marketing", label: "Marketing", required: true },
    { key: "branch", label: "Cabang", required: true },
    {
      key: "status",
      label: "Status",
      required: true,
      type: "select",
      options: ["Active", "Inactive"],
    },
  ],
  columns: [
    { key: "id", label: "ID", width: "w-20" },
    { key: "name", label: "Nama" },
    { key: "account", label: "Akun" },
    { key: "phone", label: "No. Telp" },
    { key: "contactName", label: "Nama Kontak" },
    { key: "marketing", label: "Marketing" },
    { key: "branch", label: "Cabang" },
    { key: "status", label: "Status", badge: true },
  ],
  rowActions: [
    { key: "edit", label: "Edit", icon: PencilSquareIcon },
    { key: "pricing", label: "Edit Harga/Koli" },
    { key: "trucking", label: "Edit Trucking" },
    { key: "delete", label: "Delete", icon: TrashIcon, destructive: true },
  ],
  tools: [
    {
      key: "template",
      label: "Download Import Template",
      icon: ArrowDownTrayIcon,
    },
    { key: "import", label: "Import Data" },
    { key: "export", label: "Export Data" },
  ],
  emptyForm: {
    name: "",
    account: "",
    phone: "",
    contactName: "",
    marketing: "",
    branch: "",
    status: "Active",
  },
  editTitle: "Customer",
};
