import { MANIFEST_DEFAULT_STATUS } from "./manifestStatus";

export { MANIFEST_COLUMNS, MANIFEST_SORTABLE_KEYS } from "./manifestColumns";
export { MANIFEST_DEFAULT_STATUS, MANIFEST_STATUS_META, MANIFEST_STATUS_OPTIONS } from "./manifestStatus";

export const MANIFEST_ENDPOINT = "/manifests";

export const MANIFEST_DEFAULT_PAGE_SIZE = 10;

export const MANIFEST_DEFAULT_FORM = {
  manifestNo: "",
  date: "",
  driver: "",
  nopol: "",
  status: MANIFEST_DEFAULT_STATUS,
};

export const MANIFEST_SEARCH_FIELDS = ["manifestNo"];

export const MANIFEST_SEED_ROWS = [
  {
    id: 1,
    manifestNo: "MAN-2026-0001",
    date: "2026-08-05",
    transit1: "Jakarta",
    transit2: "Cikarang",
    transit3: "Bandung",
    transit4: "-",
    transit5: "-",
    tujuan: "Surabaya",
    status: "Transit",
    totAwb: 24,
    totKoli: 58,
    totKg: 1240,
    totVolume: 17.5,
    totBiaya: 3650000,
    driver: "Rudi Hartono",
    nopol: "B 9087 KXZ",
    kendaraan: "Rudi Hartono / B 9087 KXZ",
  },
  {
    id: 2,
    manifestNo: "MAN-2026-0002",
    date: "2026-08-04",
    transit1: "Semarang",
    transit2: "Solo",
    transit3: "Madiun",
    transit4: "-",
    transit5: "-",
    tujuan: "Malang",
    status: "Inbound",
    totAwb: 18,
    totKoli: 41,
    totKg: 960,
    totVolume: 11.2,
    totBiaya: 2840000,
    driver: "Budi Santoso",
    nopol: "B 9234 TKL",
    kendaraan: "Budi Santoso / B 9234 TKL",
  },
  {
    id: 3,
    manifestNo: "MAN-2026-0003",
    date: "2026-08-03",
    transit1: "Bekasi",
    transit2: "Cirebon",
    transit3: "Tegal",
    transit4: "Pekalongan",
    transit5: "-",
    tujuan: "Semarang",
    status: "Completed",
    totAwb: 32,
    totKoli: 76,
    totKg: 1815,
    totVolume: 22.4,
    totBiaya: 4780000,
    driver: "Andi Prasetyo",
    nopol: "D 7041 QW",
    kendaraan: "Andi Prasetyo / D 7041 QW",
  },
  {
    id: 4,
    manifestNo: "MAN-2026-0004",
    date: "2026-08-02",
    transit1: "Tangerang",
    transit2: "-",
    transit3: "-",
    transit4: "-",
    transit5: "-",
    tujuan: "Bandung",
    status: "Draft",
    totAwb: 9,
    totKoli: 19,
    totKg: 420,
    totVolume: 5.4,
    totBiaya: 1120000,
    driver: "Joko Widodo",
    nopol: "B 1189 LHT",
    kendaraan: "Joko Widodo / B 1189 LHT",
  },
  {
    id: 5,
    manifestNo: "MAN-2026-0005",
    date: "2026-08-01",
    transit1: "Jakarta",
    transit2: "Bogor",
    transit3: "Cianjur",
    transit4: "Sukabumi",
    transit5: "-",
    tujuan: "Tasikmalaya",
    status: "Transit",
    totAwb: 27,
    totKoli: 64,
    totKg: 1495,
    totVolume: 19.8,
    totBiaya: 3925000,
    driver: "Hendra Gunawan",
    nopol: "B 8871 NAR",
    kendaraan: "Hendra Gunawan / B 8871 NAR",
  },
];
